name: frontend
packages:
  - modules/*

command:
  bootstrap:
    run: melos exec -- flutter pub get
    runPubGetInParallel: false

scripts:
  version:
    run: melos version --no-publish --yes
  gen-l10n:
    exec: flutter gen-l10n
    ignoreErrors: true